name: wallet-app-ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['22.x', '19.x', '18.x']
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install pnpm package globally
        run: npm install -g pnpm
      
      - name: Install dependencies
        run: pnpm install

      - name: Run build
        run: pnpm run build --if-present
      
      - name: Run tests
        run: pnpm test
      
      - name: Test Reports
        uses: dorny/test-reporter@v1
        if: always()  # Ensure test report step runs regardless of success or failure
        with:
          name: Test Results
          path: reports/test-results.json
          reporter: jest-json